version: '3.7'

services:

  hello-world:
    container_name: hello-world
    image: amirkaramian/sample:latest
     build:
       context: ./hello-world
       dockerfile: Dockerfile
     volumes:
       - '.:/app'
       - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  hello:
    container_name: hello
    image: amirkaramian/sample2:latest
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - .:/code      